version: '3'

services:
  cpp-container:
    build: .
    container_name: schelling-segregation
    stdin_open: true # docker run -i
    tty: true
    environment:
      - DISPLAY=$DISPLAY
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:
      - '3000:3000'
